import { NavLink } from 'react-router-dom';

import { LANGUAGE_LABELS } from '../lib/constants';
import { useAppState } from '../lib/app-state';


function navClassName(isActive) {
  return isActive
    ? 'rounded-full bg-slate-900 px-4 py-2 text-sm font-semibold text-white'
    : 'rounded-full px-4 py-2 text-sm font-semibold text-slate-600 transition hover:bg-white hover:text-slate-900';
}


export function AppShell({ children }) {
  const { finalizePath, language, sessionPath, setLanguage } = useAppState();

  return (
    <div className="min-h-screen px-4 py-5 md:px-6 lg:px-8">
      <div className="mx-auto flex max-w-7xl flex-col gap-6">
        <header className="surface px-5 py-4 md:px-6">
          <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
            <div>
              <p className="eyebrow">Therapy Cards</p>
              <h1 className="font-display text-2xl font-semibold text-slate-900">Reflection Workspace</h1>
              <p className="mt-1 max-w-2xl text-sm text-slate-600">
                Browser-only session state, configurable themes, and on-demand PDF reports generated by FastAPI.
              </p>
            </div>
            <div className="flex flex-col gap-3 sm:flex-row sm:items-center">
              <nav className="flex flex-wrap gap-2">
                <NavLink to={sessionPath} className={({ isActive }) => navClassName(isActive)}>
                  Session
                </NavLink>
                <NavLink to={finalizePath} className={({ isActive }) => navClassName(isActive)}>
                  Finalize Session
                </NavLink>
                <NavLink to="/configuration" className={({ isActive }) => navClassName(isActive)}>
                  Configuration
                </NavLink>
              </nav>
              <label className="flex items-center gap-2 rounded-full border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-700">
                <span>Language</span>
                <select
                  value={language}
                  onChange={(event) => setLanguage(event.target.value)}
                  className="bg-transparent text-sm outline-none"
                >
                  {Object.entries(LANGUAGE_LABELS).map(([value, label]) => (
                    <option key={value} value={value}>
                      {label}
                    </option>
                  ))}
                </select>
              </label>
            </div>
          </div>
        </header>
        <main>{children}</main>
      </div>
    </div>
  );
}
