const SESSION_UI_TEXT = {
  en: {
    common: {
      session: 'Session',
      finalizeSession: 'Finalize Session',
      configuration: 'Configuration',
      language: 'Language',
      logout: 'Log out',
      selected: 'Selected',
      zoomCard: 'Zoom card',
      closePreview: 'Close preview',
      openLink: 'Open link',
      copyLink: 'Copy link',
      copied: 'Copied',
      copyFailed: 'Copy failed',
      label: 'Label',
      sessionName: 'Session name',
      expires: 'Expires',
      shareUrl: 'Share URL',
      backToHome: 'Back to home',
      openConfiguration: 'Open configuration',
    },
    select: {
      loading: 'Loading session setup...',
      opening: 'Opening session...',
      unavailableTitle: 'Session unavailable',
      inviteRequired: 'A valid session link is required. New session links can only be created by an admin.',
      blockedTitle: 'Session is blocked',
      blockedDescription: 'This direct session link is disabled in shared configuration, so the session workspace will not open until it is unblocked.',
      selectionTitle: 'My Selection',
      availableCards: 'Available cards',
      finalizeSelection: 'Finalize Selection',
      clearSelection: 'Clear Selection',
      allCards: 'All',
      filterToolbarLabel: 'Filter cards by label',
      noCardsTitle: 'No cards match this filter.',
      noCardsDescription: 'This session label does not currently have any cards assigned.',
      showAllCards: 'Show all cards',
      slotPrefix: 'Slot',
      emptySlotHint: 'Drop or click to fill',
      moveEarlier: 'Move earlier',
      moveLater: 'Move later',
      dragCard: 'Drag card',
      removeCard: 'Remove card',
      previewTitle: 'Card preview',
    },
    overview: {
      unavailableTitle: 'Session unavailable',
      noCardsTitle: 'No cards selected yet',
      noCardsDescription: 'Choose at least one card in the session page before opening finalize session.',
      openSession: 'Open Session',
      title: 'Selected cards',
      backToSession: 'Back to session',
      printToPdf: 'Print to PDF',
      preparingPdf: 'Preparing PDF...',
      notes: 'Notes:',
      notesPlaceholder: 'Add notes here',
      printError: 'Unable to generate the PDF report.',
    },
    sessionManagement: {
      loadingAuth: 'Checking admin session...',
      loginRequiredTitle: 'Login required',
      loginRequiredDescription: 'Session management is only available when you are logged in as an admin.',
      title: 'Session management',
      description: 'Create 24-hour client links, review all currently active sessions, and clear them when needed. Expired sessions are removed automatically whenever this page is opened or refreshed.',
      backToConfiguration: 'Back to configuration',
      refreshSessions: 'Refresh sessions',
      refreshingSessions: 'Refreshing...',
      createSession: 'Create session',
      createDescription: 'Give the session a name, choose the active label, and generate a unique client link that stays active for 24 hours.',
      createButton: 'Create session',
      creatingButton: 'Creating...',
      sessionNamePlaceholder: 'Enter session name',
      clearSessions: 'Clear sessions',
      clearDescription: 'Remove all active session links and clear the local session state saved in this browser.',
      clearingButton: 'Clearing...',
      overviewSessions: 'Overview sessions',
      activeCountSuffix: 'active',
      loadingSessions: 'Loading active sessions...',
      noActiveSessionsTitle: 'No active sessions',
      noActiveSessionsDescription: 'Create a session link above when you want to open a new client session.',
      createLinkError: 'Unable to create a session link.',
      loadSessionsError: 'Unable to load active sessions.',
      clearSessionsError: 'Unable to clear active sessions.',
      loadingConfiguration: 'Loading configuration...',
      configurationUnavailableTitle: 'Configuration unavailable',
      noLabelsAssigned: 'No labels currently have cards assigned. Add card labels first before creating a session.',
      copyLink: 'Copy link',
      copyFailed: 'Copy failed',
      copied: 'Copied',
      openLink: 'Open link',
      sessionClearedSingular: 'active session cleared.',
      sessionClearedPlural: 'active sessions cleared.',
    },
    invite: {
      unavailableTitle: 'Session link unavailable',
      unavailableDescription: 'This session link is unavailable.',
      opening: 'Opening session link...',
    },
  },
  nl: {
    common: {
      session: 'Sessie',
      finalizeSession: 'Sessie afronden',
      configuration: 'Configuratie',
      language: 'Taal',
      logout: 'Uitloggen',
      selected: 'Geselecteerd',
      zoomCard: 'Kaart vergroten',
      closePreview: 'Voorbeeld sluiten',
      openLink: 'Link openen',
      copyLink: 'Link kopieren',
      copied: 'Gekopieerd',
      copyFailed: 'Kopieren mislukt',
      label: 'Label',
      sessionName: 'Sessienaam',
      expires: 'Verloopt',
      shareUrl: 'Deellink',
      backToHome: 'Terug naar start',
      openConfiguration: 'Open configuratie',
    },
    select: {
      loading: 'Sessie-instelling laden...',
      opening: 'Sessie openen...',
      unavailableTitle: 'Sessie niet beschikbaar',
      inviteRequired: 'Een geldige sessielink is vereist. Nieuwe sessielinks kunnen alleen door een admin worden gemaakt.',
      blockedTitle: 'Sessie is geblokkeerd',
      blockedDescription: 'Deze directe sessielink is uitgeschakeld in de gedeelde configuratie en opent daarom niet.',
      selectionTitle: 'Mijn selectie',
      availableCards: 'Beschikbare kaarten',
      finalizeSelection: 'Selectie afronden',
      clearSelection: 'Selectie wissen',
      allCards: 'Alle',
      filterToolbarLabel: 'Filter kaarten op label',
      noCardsTitle: 'Geen kaarten voor dit filter.',
      noCardsDescription: 'Aan dit sessielabel zijn momenteel geen kaarten gekoppeld.',
      showAllCards: 'Toon alle kaarten',
      slotPrefix: 'Vak',
      emptySlotHint: 'Sleep of klik om te vullen',
      moveEarlier: 'Eerder zetten',
      moveLater: 'Later zetten',
      dragCard: 'Kaart slepen',
      removeCard: 'Kaart verwijderen',
      previewTitle: 'Kaartvoorbeeld',
    },
    overview: {
      unavailableTitle: 'Sessie niet beschikbaar',
      noCardsTitle: 'Nog geen kaarten geselecteerd',
      noCardsDescription: 'Kies eerst minimaal een kaart in de sessie voordat je afronden opent.',
      openSession: 'Open sessie',
      title: 'Geselecteerde kaarten',
      backToSession: 'Terug naar sessie',
      printToPdf: 'Print naar PDF',
      preparingPdf: 'PDF voorbereiden...',
      notes: 'Notities:',
      notesPlaceholder: 'Voeg hier notities toe',
      printError: 'PDF kan niet worden gemaakt.',
    },
    sessionManagement: {
      loadingAuth: 'Adminsessie controleren...',
      loginRequiredTitle: 'Login vereist',
      loginRequiredDescription: 'Sessiebeheer is alleen beschikbaar wanneer je bent ingelogd als admin.',
      title: 'Sessiebeheer',
      description: 'Maak 24-uurs cliëntlinks, bekijk alle actieve sessies en wis ze wanneer nodig. Verlopen sessies worden automatisch verwijderd zodra deze pagina wordt geopend of vernieuwd.',
      backToConfiguration: 'Terug naar configuratie',
      refreshSessions: 'Sessies vernieuwen',
      refreshingSessions: 'Vernieuwen...',
      createSession: 'Sessie maken',
      createDescription: 'Geef de sessie een naam, kies het actieve label en maak een unieke cliëntlink die 24 uur geldig blijft.',
      createButton: 'Sessie maken',
      creatingButton: 'Maken...',
      sessionNamePlaceholder: 'Voer sessienaam in',
      clearSessions: 'Sessies wissen',
      clearDescription: 'Verwijder alle actieve sessielinks en wis de lokale sessiestatus in deze browser.',
      clearingButton: 'Wissen...',
      overviewSessions: 'Overzicht sessies',
      activeCountSuffix: 'actief',
      loadingSessions: 'Actieve sessies laden...',
      noActiveSessionsTitle: 'Geen actieve sessies',
      noActiveSessionsDescription: 'Maak hierboven een sessielink wanneer je een nieuwe cliëntsessie wilt openen.',
      createLinkError: 'Sessielink kan niet worden gemaakt.',
      loadSessionsError: 'Actieve sessies kunnen niet worden geladen.',
      clearSessionsError: 'Actieve sessies kunnen niet worden gewist.',
      loadingConfiguration: 'Configuratie laden...',
      configurationUnavailableTitle: 'Configuratie niet beschikbaar',
      noLabelsAssigned: 'Er zijn nog geen labels aan kaarten gekoppeld. Voeg eerst kaartlabels toe voordat je een sessie maakt.',
      copyLink: 'Link kopieren',
      copyFailed: 'Kopieren mislukt',
      copied: 'Gekopieerd',
      openLink: 'Link openen',
      sessionClearedSingular: 'actieve sessie gewist.',
      sessionClearedPlural: 'actieve sessies gewist.',
    },
    invite: {
      unavailableTitle: 'Sessielink niet beschikbaar',
      unavailableDescription: 'Deze sessielink is niet beschikbaar.',
      opening: 'Sessielink openen...',
    },
  },
  ro: {
    common: {
      session: 'Sesiune',
      finalizeSession: 'Finalizeaza sesiunea',
      configuration: 'Configuratie',
      language: 'Limba',
      logout: 'Deconectare',
      selected: 'Selectat',
      zoomCard: 'Mareste cardul',
      closePreview: 'Inchide previzualizarea',
      openLink: 'Deschide linkul',
      copyLink: 'Copiaza linkul',
      copied: 'Copiat',
      copyFailed: 'Copiere esuata',
      label: 'Eticheta',
      sessionName: 'Numele sesiunii',
      expires: 'Expira',
      shareUrl: 'Link de partajare',
      backToHome: 'Inapoi la start',
      openConfiguration: 'Deschide configuratia',
    },
    select: {
      loading: 'Se incarca sesiunea...',
      opening: 'Se deschide sesiunea...',
      unavailableTitle: 'Sesiune indisponibila',
      inviteRequired: 'Este necesar un link de sesiune valid. Linkurile noi pot fi create doar de un administrator.',
      blockedTitle: 'Sesiunea este blocata',
      blockedDescription: 'Acest link direct de sesiune este dezactivat in configuratia comuna si nu poate fi deschis.',
      selectionTitle: 'Selectia mea',
      availableCards: 'Carduri disponibile',
      finalizeSelection: 'Finalizeaza selectia',
      clearSelection: 'Goleste selectia',
      allCards: 'Toate',
      filterToolbarLabel: 'Filtreaza cardurile dupa eticheta',
      noCardsTitle: 'Nu exista carduri pentru acest filtru.',
      noCardsDescription: 'Aceasta eticheta de sesiune nu are in prezent carduri atribuite.',
      showAllCards: 'Arata toate cardurile',
      slotPrefix: 'Slot',
      emptySlotHint: 'Trage sau apasa pentru a completa',
      moveEarlier: 'Muta mai devreme',
      moveLater: 'Muta mai tarziu',
      dragCard: 'Trage cardul',
      removeCard: 'Elimina cardul',
      previewTitle: 'Previzualizare card',
    },
    overview: {
      unavailableTitle: 'Sesiune indisponibila',
      noCardsTitle: 'Nu exista carduri selectate',
      noCardsDescription: 'Alege cel putin un card in pagina de sesiune inainte sa finalizezi.',
      openSession: 'Deschide sesiunea',
      title: 'Carduri selectate',
      backToSession: 'Inapoi la sesiune',
      printToPdf: 'Printeaza PDF',
      preparingPdf: 'Se pregateste PDF-ul...',
      notes: 'Notite:',
      notesPlaceholder: 'Adauga notite aici',
      printError: 'PDF-ul nu poate fi generat.',
    },
    sessionManagement: {
      loadingAuth: 'Se verifica sesiunea de administrator...',
      loginRequiredTitle: 'Este necesara autentificarea',
      loginRequiredDescription: 'Administrarea sesiunilor este disponibila doar dupa autentificarea administratorului.',
      title: 'Administrare sesiuni',
      description: 'Creeaza linkuri de client valabile 24 de ore, vezi toate sesiunile active si sterge-le cand este nevoie. Sesiunile expirate sunt eliminate automat cand aceasta pagina este deschisa sau reimprospatata.',
      backToConfiguration: 'Inapoi la configuratie',
      refreshSessions: 'Reimprospateaza sesiunile',
      refreshingSessions: 'Se reimprospateaza...',
      createSession: 'Creeaza sesiune',
      createDescription: 'Da un nume sesiunii, alege eticheta activa si genereaza un link unic de client valabil 24 de ore.',
      createButton: 'Creeaza sesiune',
      creatingButton: 'Se creeaza...',
      sessionNamePlaceholder: 'Introdu numele sesiunii',
      clearSessions: 'Sterge sesiunile',
      clearDescription: 'Elimina toate linkurile active si sterge starea locala a sesiunilor din acest browser.',
      clearingButton: 'Se sterge...',
      overviewSessions: 'Prezentare sesiuni',
      activeCountSuffix: 'active',
      loadingSessions: 'Se incarca sesiunile active...',
      noActiveSessionsTitle: 'Nu exista sesiuni active',
      noActiveSessionsDescription: 'Creeaza mai sus un link de sesiune atunci cand vrei sa deschizi o sesiune noua pentru client.',
      createLinkError: 'Linkul de sesiune nu poate fi creat.',
      loadSessionsError: 'Sesiunile active nu pot fi incarcate.',
      clearSessionsError: 'Sesiunile active nu pot fi sterse.',
      loadingConfiguration: 'Se incarca configuratia...',
      configurationUnavailableTitle: 'Configuratia nu este disponibila',
      noLabelsAssigned: 'Nicio eticheta nu are carduri atribuite. Adauga mai intai etichetele cardurilor inainte sa creezi o sesiune.',
      copyLink: 'Copiaza linkul',
      copyFailed: 'Copiere esuata',
      copied: 'Copiat',
      openLink: 'Deschide linkul',
      sessionClearedSingular: 'sesiune activa stearsa.',
      sessionClearedPlural: 'sesiuni active sterse.',
    },
    invite: {
      unavailableTitle: 'Link de sesiune indisponibil',
      unavailableDescription: 'Acest link de sesiune nu este disponibil.',
      opening: 'Se deschide linkul de sesiune...',
    },
  },
};


export function getSessionUiText(language = 'en') {
  return SESSION_UI_TEXT[language] || SESSION_UI_TEXT.en;
}
